In [7]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().resolve().parent
sys.path.append(str(PROJECT_ROOT / "src"))

from bdtools.io import run_etl

In [2]:
df, calidad_datos = run_etl()

df.head()

,id_caso,anio,mes,dia,codigo_dane_de_municipio,municipio,departamento,region,modalidad,presunto_responsable,...,forma_de_vinculacion,tipo_de_vinculacion,latitud_longitud,anio_valido,mes_valido,dia_valido,longitud,latitud,decada,total_hechos
0,152.888,2.004,4,0,05585,PUERTO NARE,ANTIOQUIA,MAGDALENA MEDIO,PERSUASIÓN,GRUPO PARAMILITAR,...,SIN INFORMACIÓN,RECLUTAMIENTO,POINT (-74.5716887665 6.2194810893),2.004,4.0,NaN,-74.571689,6.219481,0s,1
1,207.556,2.001,4,25,05756,SONSON,ANTIOQUIA,ORIENTE ANTIOQUEÑO,PERSUASIÓN,GRUPO PARAMILITAR,...,INDIVIDUAL,RECLUTAMIENTO,POINT (-74.82807326 5.837681474),2.001,4.0,25.0,-74.828073,5.837681,0s,1
2,209.268,0.000,0,0,05234,DABEIBA,ANTIOQUIA,OCCIDENTE ANTIOQUEÑO,DESCONOCIDA,GUERRILLA,...,INDIVIDUAL,RECLUTAMIENTO,POINT (-76.31426328 6.992243782),NaN,NaN,NaN,-76.314263,6.992244,SIN FECHA,0
3,225.057,1.988,0,0,68689,SAN VICENTE DE CHUCURI,SANTANDER,MAGDALENA MEDIO,COACCIÓN,GUERRILLA,...,INDIVIDUAL,RECLUTAMIENTO,POINT (-73.53900334 6.894292346),1.988,NaN,NaN,-73.539003,6.894292,0s,0
4,228.661,1.998,2,15,66456,MISTRATO,RISARALDA,EJE CAFETERO,PERSUASIÓN,GUERRILLA,...,INDIVIDUAL,RECLUTAMIENTO,POINT (-75.90432634 5.416268487),1.998,2.0,15.0,-75.904326,5.416268,0s,0

In [3]:
calidad_datos.head(10)

,columna,tipo,nulos,porcentaje_nulos,valores_unicos,registros
0,dia_valido,float64,11967,69.57,31,17201
1,mes_valido,float64,11578,67.31,12,17201
2,anio_valido,float64,11176,64.97,50,17201
3,dia,int64,0,0.00,32,17201
4,id_caso,float64,0,0.00,17201,17201
5,anio,float64,0,0.00,51,17201
6,mes,int64,0,0.00,13,17201
7,region,string,0,0.00,76,17201
8,modalidad,string,0,0.00,5,17201
9,presunto_responsable,string,0,0.00,11,17201

EDA Y ESTADISTICA DESCRIPTIVA

In [9]:
from bdtools.eda import build_eda_reports
from bdtools.statistics import build_statistics_reports

ImportError: cannot import name 'EDA_COLUMNS' from 'bdtools.config' (C:\Users\HOME\Documents\Enfasis Big Data Tools\Proyecto\proyectofinalbdtools_starter\src\bdtools\config.py)

In [4]:
eda_outputs = build_eda_reports(df)

eda_outputs["resumen_general"]

NameError: name 'build_eda_reports' is not defined